# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/Toni-SM/skrl/discussions
    about: Please ask questions on the Discussions tab
